default: &default
  margin_sites:
    flexible: 'http://reuters.com'
    fixed: 'https://developer.github.com/v3/#http-redirects'
    prestige: 'http://www.yourlocalguardian.co.uk/sport/rugby/rss/'
  margin_queries:
    flexible: 'a'
    fixed: 'status'
    prestige: 'pubdate'

development:
  <<: *default
  secret_key_base: caa992309024ed4cab86c54c8f115d10ccdd6ae1bd9bbb0c1527b8ecff2cacbe13cee0e31ff4e192860aa016b233ae4989c7fe10c28b2fa642cacd0c5bb79445

test:
  <<: *default
  secret_key_base: 516c1332f2886cfa534ce744fc46920dac0e340c5af1fecabc9ff302b0a10d1ac67e97479ebc63a12cce87bb413da196d8b0367f58b159b3b2e0aab6950d4c4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
